Repository Infineon/Infineon-Design-System-Bootstrap, pull requests merged in 2022-10, with the labels that each got.

#28 Github actions modification, so canary release goes to github and doe…
  .github/workflows/main.yml
  package.json
Labels: minor

#29 repository name url fixed in package.json
  package.json
Labels: patch

#31 update package json
  package.json
Labels: bug, patch

#32 removed closed from PR types that trigger a new canary release as it …
  .github/workflows/main.yml
Labels: patch

#39 update buttons color naming for storybook controls
  src/button-group/ButtonGroup.jsx
  src/button-group/ButtonGroup.stories.jsx
  src/button/Button.jsx
  src/button/Button.stories.jsx
Labels: patch

#42 replace old design tokens with the new ones
  package-lock.json
  package.json
  src/accordion/_accordion.scss
  src/alert/Alert.jsx
  src/alert/Alert.stories.jsx
  src/alert/_alert.scss
  src/badge/_badge.scss
  src/bootstrap-theme.scss
  src/breadcrumb/_breadcrumb.scss
  src/button-back-to-top/_button-back-to-top.scss
  src/button-badge-on-icon/ButtonBadgeOnIcon.stories.jsx
  src/button-badge-on-icon/_button-badge-on-icon.scss
  src/button-group/_button-group.scss
  src/button/_button.scss
  src/carousel/_carousel.scss
  src/content-navigation/_content-navigation.scss
  src/dropdowns/Dropdown.jsx
  src/dropdowns/_dropdown.scss
  src/footer/_footer.scss
  src/form-elements/_form-check.scss
  src/form-elements/_form-elements.scss
  src/hero-banner/HeroBanner.stories.jsx
  src/hero-banner/_hero-banner.scss
  src/link/_link.scss
  src/list-group/ListGroup.stories.jsx
  src/list-group/_list-group.scss
  src/modal/Modal.stories.jsx
  src/modal/_modal.scss
  src/nav-bar/_nav-bar.scss
  src/pagination/_pagination.scss
  src/popover/_popover.scss
  src/progress-bar/_progress-bar.scss
  src/spinner/_spinner.scss
  src/table/_table.scss
  src/tooltip/_tooltip.scss
Labels: major

#43 update active state on button
  src/button/Button.jsx
  src/button/Button.stories.jsx
  src/button/_button.scss
Labels: minor
